--- #YAML:1.0
name:               Geo-ReadGRIB
version:            1.4
abstract:           Perl extension that gives read access to GRIB weather data files
author:
    - Frank Cox <frank.l.cox@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
